### ISSUE TITLE
Name and documentation of `cv_search`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#154]
I wonder whether the name and the documentation of `project()`'s, `varsel()`'s, and `cv_varsel()`'s argument `cv_search` makes sense.

The documentation from `project()` says about `cv_search`:

> If TRUE, then the projected coefficients after L1-selection are computed without any penalization (or using only the regularization determined by regul). If FALSE, then the coefficients are the solution from the L1-penalized projection. This option is relevant only if L1-search was used. Default is TRUE for genuine reference models and FALSE if object is datafit (see init_refmodel).

However, when looking at the source code of `.get_submodels()` (to which `project()`, `varsel()`, and `cv_varsel()` pass their argument `cv_search`), `cv_search` seems to be relevant for non-L1 search, too. I guess the comment from [these lines](https://github.com/stan-dev/projpred/blob/dc1c3e473c8df2298e956c406499ddac941e5c5f/R/projfun.R#L50-L54) might be more up-to-date than the documentation. If that comment is correct, I think `cv_search` should be renamed to something like `reproject` (or `refit_proj` which occurs on branch `workflow` and seems to be related to `cv_search`?).

**Comment by jpiironen** [comment]
This documentation item you copy-pasted above is written by me a long time ago, but it is actually for an input argument that at that time was called `relax`. I don't know what has happened, apparently the `relax` argument has been removed at some point (@AlejandroCatalina ?) and the documentation has gotten corrupted so that the documentation for `cv_search` is completely wrong. 

I checked out some very old commit, and it seems at that time the `cv_search` was called `validate_search` and the corresponding documentation item was: 
```
Whether to cross-validate also the selection process, that is, whether to perform
selection separately for each fold. Default is TRUE and we strongly recommend not setting this
to FALSE, because this is known to bias the accuracy estimates for the selected submodels.
However, setting this to FALSE can sometimes be useful because comparing the results to the case
where this parameter is TRUE gives idea how strongly the feature selection is (over)fitted to the
data (the difference corresponds to the search degrees of freedom or the effective number
of parameters introduced by the selection process).
```

By the way, I don't quite get why `cv_search` is also an argument to `varsel`, because `varsel` does not perform cross-validation. It should only be an argument to `cv_varsel`.

**Comment by AlejandroCatalina** [comment]
Yeah, the reason is that we introduced many changes at some point but we didn’t resync the whole documentation. I agree there are some things to fix and polish, including the argument name cv_search because it does not correspond to the functionality in varsel for instance. I hope to get some time to do these small fixes.

Best,
Alejandro

**Comment by fweber144** [comment]
Fixed in `develop`, so a corresponding label may be added here.
