### ISSUE TITLE
Warnings with `nloo` and `validate_search = FALSE`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#172]
In `cv_varsel()`, the combination of `nloo` (set to a value smaller than the number of observations) together with `validate_search = FALSE` leads to warnings:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  data = mydat,
                  seed = 1140350788)
library(projpred)
mycvvs <- cv_varsel(myfit, nloo = nrow(mydat) - 1, validate_search = FALSE,
                    nclusters = 2, nclusters_pred = 3, seed = 734523)

```
the warnings being
```
Warning messages:
1: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
2: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
3: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
4: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
5: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
6: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
```
Are these warnings something to worry about? I guess they come from https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/extend_family.R#L129-L132 but I'm not sure about that.

**Comment by AlejandroCatalina** [comment]
The cause of these warnings is probably due to weights being the full vector of weights instead of selecting the nloo weights only. I’ll look into it. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Frank Weber ***@***.***>
Sent: Wednesday, July 14, 2021 3:52:58 PM
To: stan-dev/projpred ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stan-dev/projpred] Warnings with `nloo` and `validate_search = FALSE` (#172)


The combination of nloo (set to a value smaller than the number of observations) together with validate_search = FALSE leads to warnings:

options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  data = mydat,
                  seed = 1140350788)
library(projpred)
mycvvs <- cv_varsel(myfit, nloo = nrow(mydat) - 1, validate_search = FALSE,
                    nclusters = 2, nclusters_pred = 3, seed = 734523)


the warnings being

Warning messages:
1: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
2: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
3: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
4: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
5: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length
6: In weights * dnorm(y, mu, dis, log = TRUE) :
  longer object length is not a multiple of shorter object length


Are these warnings something to worry about? I guess they come from https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/extend_family.R#L129-L132 but I'm not sure about that.
