### ISSUE TITLE
proj_linpred selects redundant terms

### ISSUE THREAD

**Issue by tmalsburg** [stan-dev/projpred#181]
There is a chance that I'm misunderstanding what the `proj_linepred` is suppose to do and specifically the description of the `nterms` paramter, but ...: When I have two predictors that are both useful on their own but redundant because they explain the same variance, `proj_linpred` will choose them both, even though that doesn't improve the predictions. In fact it worsens the prediction because it drops a predictor that could have been useful in favor of the redundant predictor.  Is that a limitation of the method or a limitation of the software?  I could provide a concrete example for illustration if that would help.

**Comment by AlejandroCatalina** [comment]
I would appreciate an example indeed. There seems to be a misconception at some point because proj_linpred doe not really select variables, they are given as solution_terms argument. If you are not passing a vsel object it might just choose the first nterms as specified in the model formula but that’s definitely not the intended use.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Titus von der Malsburg ***@***.***>
Sent: Wednesday, July 21, 2021 4:08:12 PM
To: stan-dev/projpred ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stan-dev/projpred] proj_linpred selects redundant terms (#181)


There is a chance that I'm misunderstanding what the proj_linepred is suppose to do and specifically the description of the nterms paramter, but ...: When I have two predictors that are both useful on their own but redundant because they explain the same variance, proj_linpred will choose them both, even though that doesn't improve the predictions. In fact it worsens the prediction because it drops a predictor that could have been useful in favor of the redundant predictor. Is that a limitation of the method or a limitation of the software? I could provide a concrete example for illustration if that would help.

**Comment by tmalsburg** [comment]
> I would appreciate an example indeed.

[Here's](https://github.com/stan-dev/projpred/files/6856089/test.zip) the data.  Code (modeled after [vignette](https://mc-stan.org/projpred/articles/quickstart_glmm.html)):

``` R
load("test.Rda")

stan_glm(Y ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9, chains = 4, data=d, seed=1) -> fit

fit %>% summary

get_refmodel(fit) -> ref
varsel(ref) -> vs

message("Ranked predictors:")
solution_terms(vs)

plot(vs, stats = c('elpd', 'rmse'))

proj <- project(vs, nterms = 4, ns = 500)
mcmc_areas(as.matrix(proj), pars = solution_terms(vs)[1:4])

par(mfrow=c(1,3))

pred <- proj_linpred(vs, newdata = d, nterms = 1, integrated = TRUE)
plot(pred$pred, d$Score, asp=1, xlim=c(70, 130), main="Only best predictor")
abline(0, 1, col="red", lwd=2)

pred <- proj_linpred(vs, newdata = d, nterms = 4, integrated = TRUE)
plot(pred$pred, d$Score, asp=1, xlim=c(70, 130), main="4 best predictors")
abline(0, 1, col="red", lwd=2)

pred <- proj_linpred(vs, newdata = d, nterms = 9, integrated = TRUE)
plot(pred$pred, d$Score, asp=1, xlim=c(70, 130), main="All predictors")
abline(0, 1, col="red", lwd=2)

```

Note how in the plot of the posteriors predictor V5 doesn't add anything (because redundant with V6). 

>  There seems to be a misconception at some point because proj_linpred doe not really select variables, they are given as solution_terms argument. If you are not passing a vsel object it might just choose the first nterms as specified in the model formula but that’s definitely not the intended use.

I suspected that I'm misunderstanding something :)  but note that the vignette (which, as a bloody beginner, I'm blindly following) uses `proj_linpred` precisely in this way (specifying `nterms` but not `solution_terms`).

**Comment by fweber144** [comment]
I would say this is a limitation of the L1 search. A forward search with
```r
vs_fw <- varsel(ref, method = "forward", seed = 547632)
print(vs_fw)
plot(vs_fw)
```
gives
```
Family: gaussian 
Link function: identity 

Formula: Y ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9
Observations: 76
Search method: forward, maximum number of terms 9
Number of clusters used for selection: 20
Number of draws used for prediction: 400
Suggested Projection Size: 4

Selection Summary:
 size solution_terms   elpd  se  diff diff.se
    0           <NA> -297.3 4.4 -21.0     4.4
    1             V6 -282.8 3.9  -6.5     2.5
    2             V9 -281.4 3.9  -5.1     2.4
    3             V3 -277.7 4.0  -1.4     1.4
    4             V1 -276.8 3.9  -0.5     0.8
    5             V7 -276.4 3.9  -0.1     0.6
    6             V5 -276.1 3.9   0.2     0.3
    7             V4 -276.2 3.9   0.1     0.3
    8             V8 -276.2 3.9   0.1     0.2
    9             V2 -276.3 4.0   0.1     0.1
```
and
![forward](https://user-images.githubusercontent.com/55132727/161077110-8d9ee8d5-589b-4113-ac30-98700a6d474b.png)
respectively. On branch `develop`, the docs (e.g. for `varsel()`) mention a limitation of L1 search. On `master` (and the current CRAN version 2.0.2), we have https://github.com/stan-dev/projpred/blob/dc1c3e473c8df2298e956c406499ddac941e5c5f/vignettes/quickstart.Rmd#L167 in the GLM vignette.

Furthermore, `cv_varsel()` gives quite different results, indicating that search and evaluation need to be cross-validated:
```r
cvvs <- cv_varsel(ref, nterms_max = 5, seed = 547632)
plot(cvvs)
```
gives
![cv_varsel](https://user-images.githubusercontent.com/55132727/161077286-ae11cef5-478b-47d3-bb6d-c4521e57ec86.png)

**Comment by tmalsburg** [comment]
Thank you very much for the response!  Seems like a pretty serious limitation of L1, no?  But the forward search seems to be doing the job alright, although I'm surprised by how much more trigger-happy it is than cv.  Thanks again.

**Comment by fweber144** [comment]
Yes, this is indeed a rather serious limitation users need to be aware of when using L1 search. I hope the new docs and vignette are sufficient.

**Comment by tmalsburg** [comment]
Just read the man page and it does mention issues with L1 but doesn't go into details (and it shouldn't because it's just a man page).  Thanks again.
