### ISSUE TITLE
NAs should be ignored if present in variables not used in the model

### ISSUE THREAD

**Issue by mcol** [stan-dev/projpred#21]
When fitting a model that uses a subset of variables from a dataframe, I would expect that missing values that are present in any of the columns not referenced by the model should be ignored. 

```
library(rstanarm)
set.seed(1234)
df <- data.frame(matrix(runif(21*500), ncol=21))
colnames(df)[21] <- "y"

## missing value in the 20th column
df$X20[99] <- NA

## model only uses the first 10 columns
model <- reformulate(colnames(df)[1:10], response="y")
fit <- stan_glm(model, data=df, iter=500, seed=1)
vs <- varsel(fit)

## Error: NAs are not allowed in 'newdata'.
```

**Comment by jpiironen** [comment]
Thanks for reporting. Unfortunately this seems to be an issue with `rstanarm`'s `posterior_linpred`.

In your example, if I call

`pred <- posterior_linpred(fit)`

or

`pred <- posterior_linpred(fit, newdata = df[,1:10])`

everything works but 

`pred <- posterior_linpred(fit, newdata = df)`

throws an error `Error: NAs are not allowed in 'newdata'.`

I think it would be possible to avoid this by modifying the code in `projpred` and passing only the corresponding columns to `posterior_linpred`, but I think it would be more intuitive if `posterior_linpred` would be able to figure this out (especially since `pred <- posterior_linpred(fit)` works although the original `df` has missing values in irrelevant columns).

Any thoughts on this one @jgabry or @bgoodri ?

**Comment by mcol** [comment]
This seems to have been fixed in https://github.com/stan-dev/rstanarm/pull/351, I was working on the CRAN version of the package. I'll see if using the git version for now is enough.

**Comment by mcol** [comment]
Indeed, the git version of `rstanarm` is fine, an so is `brms`.
