### ISSUE TITLE
Refactors and bugs in `.init_submodel()`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#242]
Currently (branch `develop`), `.init_submodel()` reads: https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/projfun.R#L89-L110

First of all, I think this can be simplified for the Gaussian family: The call to `pseudo_data()` is not necessary because for the Gaussian family with `f = 0`, the following holds within `pseudo_data()`:
* `family$linkinv(f + offset)` is equal to `offset`.
* `family$mu.eta()` gives all-ones.
* `family$variance()` gives all-ones.

Therefore, within `pseudo_data()`, https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/glmfun.R#L38 is equivalent to `z <- y - offset` and https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/glmfun.R#L66 is equivalent to `wobs <- weights`.

More importantly however, I think there are some bugs in `.init_submodel()` (the key to seeing them is the simplifying refactor shown above as well as the fact that `ref_predfun()` is supposed to exclude offsets, see #186):

* For the Gaussian family, the final `ref$mu` has offsets subtracted once again (compared to `refmodel$mu` which already excludes them) whereas the submodel's `mu` includes them. See reprex 1 below.
* For non-Gaussian families, the final `ref$mu` excludes the offsets (because it basically corresponds to `refmodel$mu`, just appropriately clustered and summarized) whereas the submodel's `mu` includes them. See reprex 2 below.
* For the `Student_t()` family, `ref$wobs` in https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/projfun.R#L103 is `NULL`, so `/ sum(wobs)` in
https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/extend_family.R#L205 divides by 0 (and apart from that, `psub` there has no element `w`, so an error is thrown, but the `Student_t()` family seems to be unfinished anyway, see also PR #233). See reprex 3 below.

I can create a PR for fixing this if you want (I have already started this locally).

Reprex 1 (the `stopifnot()` calls should pass, so the logical expressions inside of them evaluate to `TRUE`):
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
dat$offscol <- 7 * dat$X6 # To have large offsets.
library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 seed = 1140350788)

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

library(projpred)
debug(projpred:::.init_submodel)
# Debug the following call until line
# `mu <- family$mu_fun(sub_fit, offset = refmodel$offset)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
stopifnot(identical(ref$mu, p_ref$mu - refmodel$offset))
stopifnot(identical(refmodel$offset, dat$offscol))
stopifnot(identical(refmodel$mu, pl_ch - dat$offscol))
## --> In `ref$mu`, offsets are subtracted twice (compared to
## `posterior_linpred()` where the offsets are included once). (Note
## that `p_ref$mu` basically corresponds to `refmodel$mu`.)
# Furthermore:
stopifnot(identical(ref$wobs, wobs))
## --> The call to pseudo_data() can be avoided (for
## `ref$mu`, see above).

```

Reprex 2:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
icpt <- -0.42
dat$offscol <- 7 * dat$X6 # To have large offsets.
set.seed(457211)
dat$y <- rbinom(nrow(dat), size = 1, prob = binomial()$linkinv(
  icpt +
    dat$offscol +
    0.8 * dat$X1
))

library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 family = binomial(link = "logit"),
                 seed = 1140350788)

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

library(projpred)
debug(projpred:::.init_submodel)
# Debug the following call until line
# `mu <- family$mu_fun(sub_fit, offset = refmodel$offset)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
stopifnot(identical(ref$mu, p_ref$mu))
stopifnot(identical(refmodel$offset, dat$offscol))
stopifnot(identical(refmodel$mu, binomial()$linkinv(pl_ch - dat$offscol)))
## --> In `ref$mu`, offsets are excluded (compared to `posterior_linpred()`
## where the offsets are included).

```

Reprex 3:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
dat$offscol <- 7 * dat$X6 # To have large offsets.
### Quick-and-dirty solution to get a Student_t() reference model:
library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 seed = 1140350788)
library(projpred)
rfit$family <- Student_t()
refm <- get_refmodel(rfit)
###

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

debug(projpred:::.init_submodel)
# Debug the following call until line
# `dis <- family$dis_fun(ref, nlist(mu), ref$wobs)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
debug(family$dis_fun)
n
stopifnot(is.null(wobs))
stopifnot(!"w" %in% names(psub))

```

**Comment by AlejandroCatalina** [comment]
Thanks for noticing this, a PR would be welcome of course.

Best,
Alex
________________________________
From: Frank Weber ***@***.***>
Sent: Tuesday, November 9, 2021 8:42:03 PM
To: stan-dev/projpred ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stan-dev/projpred] Refactors and bugs in `.init_submodel()` (Issue #242)


Currently (branch develop), .init_submodel() reads: https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/projfun.R#L89-L110

First of all, I think this can be simplified for the Gaussian family: The call to pseudo_data() is not necessary because for the Gaussian family with f = 0, the following holds within pseudo_data():

  *   family$linkinv(f + offset) is equal to offset.
  *   family$mu.eta() gives all-ones.
  *   family$variance() gives all-ones.

Therefore, within pseudo_data(), https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/glmfun.R#L38 is equivalent to z <- y - offset and https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/glmfun.R#L66 is equivalent to wobs <- weights.

More importantly however, I think there are some bugs in .init_submodel() (the key to seeing them is the simplifying refactor shown above as well as the fact that ref_predfun() is supposed to exclude offsets, see #186<https://github.com/stan-dev/projpred/issues/186>):

  *   For the Gaussian family, the final ref$mu has offsets subtracted once again (compared to refmodel$mu which already excludes them) whereas the submodel's mu includes them. See reprex 1 below.
  *   For non-Gaussian families, the final ref$mu excludes the offsets (because it basically corresponds to refmodel$mu, just appropriately clustered and summarized) whereas the submodel's mu includes them. See reprex 2 below.
  *   For the Student_t() family, ref$wobs in https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/projfun.R#L103 is NULL, so / sum(wobs) in
https://github.com/stan-dev/projpred/blob/ef3cfc238ca83fcf854e34ab3cdb1c57a17ffa79/R/extend_family.R#L205 divides by 0 (and apart from that, psub there has no element w, so an error is thrown, but the Student_t() family seems to be unfinished anyway, see also PR #233<https://github.com/stan-dev/projpred/pull/233>). See reprex 3 below.

I can create a PR for fixing this if you want (I have already started this locally).

Reprex 1 (the stopifnot() calls should pass, so the logical expressions inside of them evaluate to TRUE):

options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
dat$offscol <- 7 * dat$X6 # To have large offsets.
library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 seed = 1140350788)

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

library(projpred)
debug(projpred:::.init_submodel)
# Debug the following call until line
# `mu <- family$mu_fun(sub_fit, offset = refmodel$offset)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
stopifnot(identical(ref$mu, p_ref$mu - refmodel$offset))
stopifnot(identical(refmodel$offset, dat$offscol))
stopifnot(identical(refmodel$mu, pl_ch - dat$offscol))
## --> In `ref$mu`, offsets are subtracted twice (compared to
## `posterior_linpred()` where the offsets are included once). (Note
## that `p_ref$mu` basically corresponds to `refmodel$mu`.)
# Furthermore:
stopifnot(identical(ref$wobs, wobs))
## --> The call to pseudo_data() can be avoided (for
## `ref$mu`, see above).


Reprex 2:

options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
icpt <- -0.42
dat$offscol <- 7 * dat$X6 # To have large offsets.
set.seed(457211)
dat$y <- rbinom(nrow(dat), size = 1, prob = binomial()$linkinv(
  icpt +
    dat$offscol +
    0.8 * dat$X1
))

library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 family = binomial(link = "logit"),
                 seed = 1140350788)

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

library(projpred)
debug(projpred:::.init_submodel)
# Debug the following call until line
# `mu <- family$mu_fun(sub_fit, offset = refmodel$offset)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
stopifnot(identical(ref$mu, p_ref$mu))
stopifnot(identical(refmodel$offset, dat$offscol))
stopifnot(identical(refmodel$mu, binomial()$linkinv(pl_ch - dat$offscol)))
## --> In `ref$mu`, offsets are excluded (compared to `posterior_linpred()`
## where the offsets are included).


Reprex 3:

options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
dat$offscol <- 7 * dat$X6 # To have large offsets.
### Quick-and-dirty solution to get a Student_t() reference model:
library(rstanarm)
rfit <- stan_glm(y ~ X1 + X2 + X3 + X4 + X5 + offset(offscol),
                 data = dat,
                 seed = 1140350788)
library(projpred)
rfit$family <- Student_t()
refm <- get_refmodel(rfit)
###

pl_ch <- t(posterior_linpred(rfit))
dimnames(pl_ch) <- NULL
### Just to show that offsets are included in posterior_linpred():
drws <- as.matrix(rfit)
drws_icpt <- drws[, "(Intercept)"]
drws_beta <- drws[
  ,
  grep("^X", colnames(drws), value = TRUE),
  drop = FALSE
]
mm <- model.matrix(
  ~ X1 + X2 + X3 + X4 + X5,
  data = dat
)
pl_man <- t(cbind(drws_icpt, drws_beta) %*% t(mm))
pl_man <- pl_man + dat$offscol
dimnames(pl_man) <- NULL
stopifnot(identical(pl_ch, pl_man))
###

debug(projpred:::.init_submodel)
# Debug the following call until line
# `dis <- family$dis_fun(ref, nlist(mu), ref$wobs)`:
prj <- project(rfit,
               solution_terms = c("X5", "X1"),
               nclusters = 3,
               seed = 46782345)
# Then, while in debugging mode:
debug(family$dis_fun)
n
stopifnot(is.null(wobs))
stopifnot(!"w" %in% names(psub))

**Comment by fweber144** [comment]
Fixed in `develop`, so a corresponding label may be added here.
