### ISSUE TITLE
Vignette gives errors after the latest changes in argument validation

### ISSUE THREAD

**Issue by jpiironen** [stan-dev/projpred#34]
After merging PR #32, the vignette now throws an error when making predictions  with `proj_linpred` or `proj_predict`. For example, executing cell
```
pred <- proj_linpred(vs, xnew=df_gaussian$x, ynew=df_gaussian$y, nv = 6, integrated = TRUE)
```
gives error
```
Error in proj_helper(object = object, xnew = xnew, offsetnew = offsetnew, : xnew must be a data.frame or a matrix. See ?proj-pred.
```

The error is raised because the `df_gaussian$x` has class `AsIs`. I guess we could get rid of this by converting that to a matrix, but I though I'd ask if you @mcol have thoughts about this since you implemented the argument validation.

**Comment by mcol** [comment]
I'll have a look at that, it's probably due to an overzealous check that wasn't caught by existing tests.

**Comment by mcol** [comment]
I read the scant information on the `AsIs` class, but could not find anywhere that explained why if matrix `x` is added to a dataframe as `I(x)` its class becomes `AsIs` instead of `c("AsIs", "matrix")` (`?I` says that the `AsIs` class is prepended to the existing classes).

```
x <- matrix(rnorm(20), 10, 2)
class(x)
# [1] "matrix"
df <- data.frame(x = I(x))
class(df$x)
# [1] "AsIs"
```

So one option would be to change this check
```
if (!inherits(xnew, c('data.frame', 'matrix')))
```
to
```
if (!inherits(xnew, c('data.frame', 'matrix', 'AsIs')))
```
but that would open up this possibility (ok, it's highly unlikely, but this would be caught by the current check):
```
bogus_asis <- I(letters)
pred <- proj_linpred(vs, xnew=bogus_asis, ynew=df_gaussian$y, nv = 6, integrated = TRUE)
# Error in rep(0, nrow(xnew)) : invalid 'times' argument
```

The other option is to update the vignette, effectively not supporting direct use of `AsIs` objects (they would still be supported if embedded in a dataframe, as the tests in `test_varsel.R` show). Note that this is what `rstanarm` does too:
```
fit <- stan_glm(y ~ x, family=gaussian(), data=df_gaussian$x)
# Error: 'data' must be a data frame.
```

**Comment by jpiironen** [comment]
I think the latter option is better. If we simply change `df_gaussian$x` and `df_binomial$x` to be matrices instead of `AsIs`, then we don't even need to change the vignette (to be honest, I didn't know they were `AsIs` at the moment). 

Can you do a PR or should I do it?

**Comment by jpiironen** [comment]
I ended up fixing it right away, since it was so straight forward. The vignette should be working now, so closing this issue.
