### ISSUE TITLE
plot.vsel shows extra xtick label

### ISSUE THREAD

**Issue by avehtari** [stan-dev/projpred#462]
See, e.g., here https://users.aalto.fi/~ave/modelselection/candy.html, there is an extra x tick label 12

![image](https://github.com/stan-dev/projpred/assets/6705400/4903995f-d2f5-4d2c-bdd7-a1a67432d188)

Another example with a gap before the last tick label
![image](https://github.com/stan-dev/projpred/assets/6705400/5e9a68f4-af2d-481e-88c9-f3a64fba3bd7)

Might be related to using text_angle

**Comment by fweber144** [comment]
Thanks for reporting; fixed now. As far as I can tell, this seemed to be a long-standing bug (I was able to track it down at least until commit https://github.com/stan-dev/projpred/commit/b05a8f41dd14a6bac6363b6462b394467f253167), so if you haven't experienced this bug before, then your last version of the candy case study (I think https://github.com/avehtari/modelselection/blob/ad0e10ce7d3a47de560609db7abe83777eed28bc/candy.Rmd is still at the old state) was probably using an even older projpred version. I'm just saying this because I was curious where the bug was introduced and if additional changes would have been necessary. But I think the fix from commit fc5d68f6265d56b7bef0d2fa93e6971db9fe23d2 should be fine.
