### ISSUE TITLE
Typo in computation of cluster centers?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#87]
Shouldn't the line https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/misc.R#L341 read
```r
centers[j, ] <- f[, ind, drop = FALSE] %*% ws
```
? However, the current use of `mu` should have no consequences---as far as I can tell, the cluster centers don't seem to be used, anyway.

(Mentioned [here](https://github.com/fweber144/projpred/blob/5088cbdfca26ccb58c366e4d31e1b2203ffc84d1/R/misc.R#L346).)

**Comment by AlejandroCatalina** [comment]
This line is actually correct. We perform clustering in the `linkfun` space but then return the family parameter `mu`, as we solve the projection in `mu` space. We then apply the link function iteratively (refer to PIRLS algorithm for more details) to actually find the projections.

We need `mu` as output instead of `linkfun(mu)` here. But I agree we could probably name this `eta` instead of `mu`, as it's not technically `mu`. For now I'm leaving this discussion open to arrive to a consensus but I'm not changing the code just yet.

**Comment by fweber144** [comment]
Ok, then using `mu` seems to be fine.

For the renaming to `eta`: Do you mean to rename `centers` to `eta`? Or `f`? Because `mu` is on the response scale (which it is supposed to), so renaming `mu` to `eta` doesn't make sense in my opinion.

**Comment by AlejandroCatalina** [comment]
I meant that mu in this case is not yet mu as the link function is not applied yet.

Best,
Alejandro

**Comment by fweber144** [comment]
Well but if the link function is not applied yet, then `mu` is on the response scale (which is correct), i.e. `mu` *is* `mu`.

Anyway, I guess we are getting our wires crossed but are agreeing upon the same thing: There's no renaming necessary.

**Comment by fweber144** [comment]
Btw, I was wrong when I said

> [...] as far as I can tell, the cluster centers don't seem to be used, anyway.

Of course they are used, I just didn't look close enough.
